//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help.EF.UsermanageDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class roleinfo
    {
        public string KeyID { get; set; }
        public string RoleName { get; set; }
        public string RoleAlias { get; set; }
        public sbyte IsValid { get; set; }
        public sbyte IsDelete { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime ModifyTime { get; set; }
    }
}
